name: portfolio
description: A Flutter portfolio project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  url_launcher: ^6.1.14
  font_awesome_flutter: ^10.6.0
  flutter_animate: ^4.5.0
  http: ^1.2.1
  fluttertoast: ^8.2.5
  animated_text_kit: ^4.2.2
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/logos/
    - assets/images/mockups/
    - assets/animations/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
    - family: NeuePower
      fonts:
        - asset: assets/fonts/neue-power/NeuePower-Ultra.ttf
